name = "rolldoradocasino-co-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradocasino.co.at"
HMAC_KEY = "502cd8238de0cc147a0c97a2a23a357d09c4a32fcf1ac554b5fb73d7fc473a5d"
COOKIE_NAME = "ziq"
PLAY_PATH = "visit"
BUTTON_ID = "p0649928ae44b40f599d7c105c219409d"
GATE_SALT = "d99c1291e8be8dc7"
