name = "rolldoradocasino-co-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradocasino.co.at"
HMAC_KEY = "502cd8238de0cc147a0c97a2a23a357d09c4a32fcf1ac554b5fb73d7fc473a5d"
COOKIE_NAME = "4pa"
PLAY_PATH = "discover"
BUTTON_ID = "p0649928ae44b40f599d7c105c219409d"
GATE_SALT = "f8c90a821a65d333"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "7u0i"
CTA_SELECTOR = ".play-button"
